### ISSUE TITLE
The log message is not complete

### ISSUE THREAD

**Issue by michaelblaess** [TinyBlueRobots/Serilog.Sinks.Syslog#10]
Hello,
we have a strange issue with the sink.
Here is the complete error message in a text file:
[errors.20190117.log](https://github.com/TinyBlueRobots/Serilog.Sinks.Syslog/files/2772384/errors.20190117.log)

When using the sink the message seems to be cropped:
![image](https://user-images.githubusercontent.com/13151198/51378988-b2840780-1b0e-11e9-943e-63ea27c64425.png)

When using other providers (e-Mail, Trace, Rolling File) we have no problem.

This is the configuration of the sink:
`  .WriteTo.Syslog("xx.xx.xx.x", 5140, "Application Name")`

Kind regards,
Michael

**Comment by JonCanning** [comment]
I've tried to recreate this by logging to Papertrail but it shows the complete message. Which Syslog server are you using?

**Comment by michaelblaess** [comment]
@JonCanning 
Thanks for investigating :+1: 

We are using GrayLog. On thursday we will do an analysis with WireShark on the server. 
I'll get back to you as soon as I know more.
