### ISSUE TITLE
Target .NET 4.5.2

### ISSUE THREAD

**Issue by taspeotis** [TinyBlueRobots/Serilog.Sinks.Syslog#5]
Hi,

Would you please consider targeting .NET 4.5.2? This is the latest supported version of the .NET 4.5.x series.

Personally I try to run the latest version of the .NET Framework, but the servers we have at work have 4.5.2 installed and will have them for the foreseeable future.

If you're open to this I'll send a PR.

Thanks.

**Comment by JonCanning** [comment]
No problem, I'm working with netstandard so didn't consider lower netfx versions. Have just pushed 1.0.8.

**Comment by taspeotis** [comment]
Thanks for the quick response. I appreciate you doing the heavy lifting of getting the NuGet package published, too!
